### PR TITLE
Removed my own deadname and added new link!

### PR DESCRIPTION
**Pull request by rileyrouth**
I sure hope I'm GitHubbing right!

### CODE REVIEW

**Comment by rileyrouth** [comment]
Hmm. Not quite doing it right. But there's also some Martial Arts Weekend lyrics for you here, I guess!

**Comment by kylebarbour** [comment]
Looks great. I'm going through it right now and will integrate it soon with some edits. What problem were you running into?

**Comment by annotatedtmg** [comment]
Looks great. I'm going through it right now and will integrate it soon with some edits. What problem were you running into?

**Comment by annotatedtmg** [comment]
Thanks for contributing the first pull request! You can see the changes [in the commit log](https://github.com/annotatedtmg/annotatedtmg/commit/16bca86b273ec3e42f59b34915fefd23f5c097b3).

Some of the lyrics were reasonably different from what I heard going through my copy of MAW. Where were you getting the lyrics from? I'm curious if they were alternate versions, we heard them differently, or something else.

By the way, if you want to see changes between what you submitted and what was merged, you can [compare the commits here](https://github.com/annotatedtmg/annotatedtmg/compare/217a9c9..16bca86). It's a little imperfect since it includes unrelated commits I made in the same time period but you can see most of the details.

**Comment by rileyrouth** [comment]
> What problem were you running into?

I wasn't expecting the PR to contain both commits, because I opened it before doing MAW. But I see how it works now, so I'll use branches if I have multiple things to commit.

> Where were you getting the lyrics from? I'm curious if they were alternate versions, we heard them differently, or something else.

I borrowed from [Genius](https://genius.com/albums/The-extra-glenns/Martial-arts-weekend) originally and filled in anything I spotted that was wrong. But all your edits look right to me; I'll use more rigour for future lyrics lifts :)

**Comment by annotatedtmg** [comment]
> > Where were you getting the lyrics from? I'm curious if they were alternate versions, we heard them differently, or something else.
> 
> I borrowed from [Genius](https://genius.com/albums/The-extra-glenns/Martial-arts-weekend) originally and filled in anything I spotted that was wrong. But all your edits look right to me; I'll use more rigour for future lyrics lifts :)

Ah, makes sense. No worries :)

**Pull request merged**
